# Generated by Django 2.1.5 on 2022-02-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220213_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='urls',
            new_name='url',
        ),
    ]
